/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AuthenticatedPersonalCenterRouteRouteImport } from './routes/_authenticated/personal-center/route'
import { Route as AuthenticatedPersonalCenterIndexRouteImport } from './routes/_authenticated/personal-center/index'
import { Route as AuthenticatedSystemRoleRouteImport } from './routes/_authenticated/system/role'
import { Route as AuthenticatedSystemOperationLogRouteImport } from './routes/_authenticated/system/operation-log'
import { Route as AuthenticatedSystemMenuRouteImport } from './routes/_authenticated/system/menu'
import { Route as AuthenticatedSystemConfigRouteImport } from './routes/_authenticated/system/config'
import { Route as AuthenticatedSystemApiRouteImport } from './routes/_authenticated/system/api'
import { Route as AuthenticatedSystemAdminRouteImport } from './routes/_authenticated/system/admin'
import { Route as AuthenticatedPromotionSceneRouteImport } from './routes/_authenticated/promotion/scene'
import { Route as AuthenticatedPromotionAdvertisingRouteImport } from './routes/_authenticated/promotion/advertising'
import { Route as AuthenticatedOperationPointRouteImport } from './routes/_authenticated/operation/point'
import { Route as AuthenticatedOperationCommentRouteImport } from './routes/_authenticated/operation/comment'
import { Route as AuthenticatedContentTagRouteImport } from './routes/_authenticated/content/tag'
import { Route as AuthenticatedContentResourceRouteImport } from './routes/_authenticated/content/resource'
import { Route as AuthenticatedContentConfigRouteImport } from './routes/_authenticated/content/config'
import { Route as AuthenticatedContentColumnRouteImport } from './routes/_authenticated/content/column'
import { Route as AuthenticatedContentCategoryRouteImport } from './routes/_authenticated/content/category'
import { Route as AuthenticatedBusinessUserRouteImport } from './routes/_authenticated/business/user'
import { Route as AuthenticatedBusinessProjectRouteImport } from './routes/_authenticated/business/project'
import { Route as AuthenticatedContentArticleRouteRouteImport } from './routes/_authenticated/content/article/route'
import { Route as AuthenticatedContentArticleIndexRouteImport } from './routes/_authenticated/content/article/index'
import { Route as AuthenticatedContentArticleNewRouteImport } from './routes/_authenticated/content/article/new'
import { Route as AuthenticatedContentArticlePostIDEditRouteImport } from './routes/_authenticated/content/article/$postID.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPersonalCenterRouteRoute =
  AuthenticatedPersonalCenterRouteRouteImport.update({
    id: '/personal-center',
    path: '/personal-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonalCenterIndexRoute =
  AuthenticatedPersonalCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPersonalCenterRouteRoute,
  } as any)
const AuthenticatedSystemRoleRoute = AuthenticatedSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemOperationLogRoute =
  AuthenticatedSystemOperationLogRouteImport.update({
    id: '/system/operation-log',
    path: '/system/operation-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemMenuRoute = AuthenticatedSystemMenuRouteImport.update({
  id: '/system/menu',
  path: '/system/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemConfigRoute =
  AuthenticatedSystemConfigRouteImport.update({
    id: '/system/config',
    path: '/system/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemApiRoute = AuthenticatedSystemApiRouteImport.update({
  id: '/system/api',
  path: '/system/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemAdminRoute =
  AuthenticatedSystemAdminRouteImport.update({
    id: '/system/admin',
    path: '/system/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionSceneRoute =
  AuthenticatedPromotionSceneRouteImport.update({
    id: '/promotion/scene',
    path: '/promotion/scene',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionAdvertisingRoute =
  AuthenticatedPromotionAdvertisingRouteImport.update({
    id: '/promotion/advertising',
    path: '/promotion/advertising',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationPointRoute =
  AuthenticatedOperationPointRouteImport.update({
    id: '/operation/point',
    path: '/operation/point',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationCommentRoute =
  AuthenticatedOperationCommentRouteImport.update({
    id: '/operation/comment',
    path: '/operation/comment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentTagRoute = AuthenticatedContentTagRouteImport.update({
  id: '/content/tag',
  path: '/content/tag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentResourceRoute =
  AuthenticatedContentResourceRouteImport.update({
    id: '/content/resource',
    path: '/content/resource',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentConfigRoute =
  AuthenticatedContentConfigRouteImport.update({
    id: '/content/config',
    path: '/content/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentColumnRoute =
  AuthenticatedContentColumnRouteImport.update({
    id: '/content/column',
    path: '/content/column',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentCategoryRoute =
  AuthenticatedContentCategoryRouteImport.update({
    id: '/content/category',
    path: '/content/category',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessUserRoute =
  AuthenticatedBusinessUserRouteImport.update({
    id: '/business/user',
    path: '/business/user',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessProjectRoute =
  AuthenticatedBusinessProjectRouteImport.update({
    id: '/business/project',
    path: '/business/project',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentArticleRouteRoute =
  AuthenticatedContentArticleRouteRouteImport.update({
    id: '/content/article',
    path: '/content/article',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentArticleIndexRoute =
  AuthenticatedContentArticleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContentArticleRouteRoute,
  } as any)
const AuthenticatedContentArticleNewRoute =
  AuthenticatedContentArticleNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedContentArticleRouteRoute,
  } as any)
const AuthenticatedContentArticlePostIDEditRoute =
  AuthenticatedContentArticlePostIDEditRouteImport.update({
    id: '/$postID/edit',
    path: '/$postID/edit',
    getParentRoute: () => AuthenticatedContentArticleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/personal-center': typeof AuthenticatedPersonalCenterRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/content/article': typeof AuthenticatedContentArticleRouteRouteWithChildren
  '/business/project': typeof AuthenticatedBusinessProjectRoute
  '/business/user': typeof AuthenticatedBusinessUserRoute
  '/content/category': typeof AuthenticatedContentCategoryRoute
  '/content/column': typeof AuthenticatedContentColumnRoute
  '/content/config': typeof AuthenticatedContentConfigRoute
  '/content/resource': typeof AuthenticatedContentResourceRoute
  '/content/tag': typeof AuthenticatedContentTagRoute
  '/operation/comment': typeof AuthenticatedOperationCommentRoute
  '/operation/point': typeof AuthenticatedOperationPointRoute
  '/promotion/advertising': typeof AuthenticatedPromotionAdvertisingRoute
  '/promotion/scene': typeof AuthenticatedPromotionSceneRoute
  '/system/admin': typeof AuthenticatedSystemAdminRoute
  '/system/api': typeof AuthenticatedSystemApiRoute
  '/system/config': typeof AuthenticatedSystemConfigRoute
  '/system/menu': typeof AuthenticatedSystemMenuRoute
  '/system/operation-log': typeof AuthenticatedSystemOperationLogRoute
  '/system/role': typeof AuthenticatedSystemRoleRoute
  '/personal-center/': typeof AuthenticatedPersonalCenterIndexRoute
  '/content/article/new': typeof AuthenticatedContentArticleNewRoute
  '/content/article/': typeof AuthenticatedContentArticleIndexRoute
  '/content/article/$postID/edit': typeof AuthenticatedContentArticlePostIDEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/business/project': typeof AuthenticatedBusinessProjectRoute
  '/business/user': typeof AuthenticatedBusinessUserRoute
  '/content/category': typeof AuthenticatedContentCategoryRoute
  '/content/column': typeof AuthenticatedContentColumnRoute
  '/content/config': typeof AuthenticatedContentConfigRoute
  '/content/resource': typeof AuthenticatedContentResourceRoute
  '/content/tag': typeof AuthenticatedContentTagRoute
  '/operation/comment': typeof AuthenticatedOperationCommentRoute
  '/operation/point': typeof AuthenticatedOperationPointRoute
  '/promotion/advertising': typeof AuthenticatedPromotionAdvertisingRoute
  '/promotion/scene': typeof AuthenticatedPromotionSceneRoute
  '/system/admin': typeof AuthenticatedSystemAdminRoute
  '/system/api': typeof AuthenticatedSystemApiRoute
  '/system/config': typeof AuthenticatedSystemConfigRoute
  '/system/menu': typeof AuthenticatedSystemMenuRoute
  '/system/operation-log': typeof AuthenticatedSystemOperationLogRoute
  '/system/role': typeof AuthenticatedSystemRoleRoute
  '/personal-center': typeof AuthenticatedPersonalCenterIndexRoute
  '/content/article/new': typeof AuthenticatedContentArticleNewRoute
  '/content/article': typeof AuthenticatedContentArticleIndexRoute
  '/content/article/$postID/edit': typeof AuthenticatedContentArticlePostIDEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/personal-center': typeof AuthenticatedPersonalCenterRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/content/article': typeof AuthenticatedContentArticleRouteRouteWithChildren
  '/_authenticated/business/project': typeof AuthenticatedBusinessProjectRoute
  '/_authenticated/business/user': typeof AuthenticatedBusinessUserRoute
  '/_authenticated/content/category': typeof AuthenticatedContentCategoryRoute
  '/_authenticated/content/column': typeof AuthenticatedContentColumnRoute
  '/_authenticated/content/config': typeof AuthenticatedContentConfigRoute
  '/_authenticated/content/resource': typeof AuthenticatedContentResourceRoute
  '/_authenticated/content/tag': typeof AuthenticatedContentTagRoute
  '/_authenticated/operation/comment': typeof AuthenticatedOperationCommentRoute
  '/_authenticated/operation/point': typeof AuthenticatedOperationPointRoute
  '/_authenticated/promotion/advertising': typeof AuthenticatedPromotionAdvertisingRoute
  '/_authenticated/promotion/scene': typeof AuthenticatedPromotionSceneRoute
  '/_authenticated/system/admin': typeof AuthenticatedSystemAdminRoute
  '/_authenticated/system/api': typeof AuthenticatedSystemApiRoute
  '/_authenticated/system/config': typeof AuthenticatedSystemConfigRoute
  '/_authenticated/system/menu': typeof AuthenticatedSystemMenuRoute
  '/_authenticated/system/operation-log': typeof AuthenticatedSystemOperationLogRoute
  '/_authenticated/system/role': typeof AuthenticatedSystemRoleRoute
  '/_authenticated/personal-center/': typeof AuthenticatedPersonalCenterIndexRoute
  '/_authenticated/content/article/new': typeof AuthenticatedContentArticleNewRoute
  '/_authenticated/content/article/': typeof AuthenticatedContentArticleIndexRoute
  '/_authenticated/content/article/$postID/edit': typeof AuthenticatedContentArticlePostIDEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/personal-center'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/content/article'
    | '/business/project'
    | '/business/user'
    | '/content/category'
    | '/content/column'
    | '/content/config'
    | '/content/resource'
    | '/content/tag'
    | '/operation/comment'
    | '/operation/point'
    | '/promotion/advertising'
    | '/promotion/scene'
    | '/system/admin'
    | '/system/api'
    | '/system/config'
    | '/system/menu'
    | '/system/operation-log'
    | '/system/role'
    | '/personal-center/'
    | '/content/article/new'
    | '/content/article/'
    | '/content/article/$postID/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/business/project'
    | '/business/user'
    | '/content/category'
    | '/content/column'
    | '/content/config'
    | '/content/resource'
    | '/content/tag'
    | '/operation/comment'
    | '/operation/point'
    | '/promotion/advertising'
    | '/promotion/scene'
    | '/system/admin'
    | '/system/api'
    | '/system/config'
    | '/system/menu'
    | '/system/operation-log'
    | '/system/role'
    | '/personal-center'
    | '/content/article/new'
    | '/content/article'
    | '/content/article/$postID/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/personal-center'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/content/article'
    | '/_authenticated/business/project'
    | '/_authenticated/business/user'
    | '/_authenticated/content/category'
    | '/_authenticated/content/column'
    | '/_authenticated/content/config'
    | '/_authenticated/content/resource'
    | '/_authenticated/content/tag'
    | '/_authenticated/operation/comment'
    | '/_authenticated/operation/point'
    | '/_authenticated/promotion/advertising'
    | '/_authenticated/promotion/scene'
    | '/_authenticated/system/admin'
    | '/_authenticated/system/api'
    | '/_authenticated/system/config'
    | '/_authenticated/system/menu'
    | '/_authenticated/system/operation-log'
    | '/_authenticated/system/role'
    | '/_authenticated/personal-center/'
    | '/_authenticated/content/article/new'
    | '/_authenticated/content/article/'
    | '/_authenticated/content/article/$postID/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/personal-center': {
      id: '/_authenticated/personal-center'
      path: '/personal-center'
      fullPath: '/personal-center'
      preLoaderRoute: typeof AuthenticatedPersonalCenterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal-center/': {
      id: '/_authenticated/personal-center/'
      path: '/'
      fullPath: '/personal-center/'
      preLoaderRoute: typeof AuthenticatedPersonalCenterIndexRouteImport
      parentRoute: typeof AuthenticatedPersonalCenterRouteRoute
    }
    '/_authenticated/system/role': {
      id: '/_authenticated/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof AuthenticatedSystemRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/operation-log': {
      id: '/_authenticated/system/operation-log'
      path: '/system/operation-log'
      fullPath: '/system/operation-log'
      preLoaderRoute: typeof AuthenticatedSystemOperationLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/menu': {
      id: '/_authenticated/system/menu'
      path: '/system/menu'
      fullPath: '/system/menu'
      preLoaderRoute: typeof AuthenticatedSystemMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/config': {
      id: '/_authenticated/system/config'
      path: '/system/config'
      fullPath: '/system/config'
      preLoaderRoute: typeof AuthenticatedSystemConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/api': {
      id: '/_authenticated/system/api'
      path: '/system/api'
      fullPath: '/system/api'
      preLoaderRoute: typeof AuthenticatedSystemApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/admin': {
      id: '/_authenticated/system/admin'
      path: '/system/admin'
      fullPath: '/system/admin'
      preLoaderRoute: typeof AuthenticatedSystemAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotion/scene': {
      id: '/_authenticated/promotion/scene'
      path: '/promotion/scene'
      fullPath: '/promotion/scene'
      preLoaderRoute: typeof AuthenticatedPromotionSceneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotion/advertising': {
      id: '/_authenticated/promotion/advertising'
      path: '/promotion/advertising'
      fullPath: '/promotion/advertising'
      preLoaderRoute: typeof AuthenticatedPromotionAdvertisingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation/point': {
      id: '/_authenticated/operation/point'
      path: '/operation/point'
      fullPath: '/operation/point'
      preLoaderRoute: typeof AuthenticatedOperationPointRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation/comment': {
      id: '/_authenticated/operation/comment'
      path: '/operation/comment'
      fullPath: '/operation/comment'
      preLoaderRoute: typeof AuthenticatedOperationCommentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/tag': {
      id: '/_authenticated/content/tag'
      path: '/content/tag'
      fullPath: '/content/tag'
      preLoaderRoute: typeof AuthenticatedContentTagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/resource': {
      id: '/_authenticated/content/resource'
      path: '/content/resource'
      fullPath: '/content/resource'
      preLoaderRoute: typeof AuthenticatedContentResourceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/config': {
      id: '/_authenticated/content/config'
      path: '/content/config'
      fullPath: '/content/config'
      preLoaderRoute: typeof AuthenticatedContentConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/column': {
      id: '/_authenticated/content/column'
      path: '/content/column'
      fullPath: '/content/column'
      preLoaderRoute: typeof AuthenticatedContentColumnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/category': {
      id: '/_authenticated/content/category'
      path: '/content/category'
      fullPath: '/content/category'
      preLoaderRoute: typeof AuthenticatedContentCategoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/user': {
      id: '/_authenticated/business/user'
      path: '/business/user'
      fullPath: '/business/user'
      preLoaderRoute: typeof AuthenticatedBusinessUserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/project': {
      id: '/_authenticated/business/project'
      path: '/business/project'
      fullPath: '/business/project'
      preLoaderRoute: typeof AuthenticatedBusinessProjectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/article': {
      id: '/_authenticated/content/article'
      path: '/content/article'
      fullPath: '/content/article'
      preLoaderRoute: typeof AuthenticatedContentArticleRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/article/': {
      id: '/_authenticated/content/article/'
      path: '/'
      fullPath: '/content/article/'
      preLoaderRoute: typeof AuthenticatedContentArticleIndexRouteImport
      parentRoute: typeof AuthenticatedContentArticleRouteRoute
    }
    '/_authenticated/content/article/new': {
      id: '/_authenticated/content/article/new'
      path: '/new'
      fullPath: '/content/article/new'
      preLoaderRoute: typeof AuthenticatedContentArticleNewRouteImport
      parentRoute: typeof AuthenticatedContentArticleRouteRoute
    }
    '/_authenticated/content/article/$postID/edit': {
      id: '/_authenticated/content/article/$postID/edit'
      path: '/$postID/edit'
      fullPath: '/content/article/$postID/edit'
      preLoaderRoute: typeof AuthenticatedContentArticlePostIDEditRouteImport
      parentRoute: typeof AuthenticatedContentArticleRouteRoute
    }
  }
}

interface AuthenticatedPersonalCenterRouteRouteChildren {
  AuthenticatedPersonalCenterIndexRoute: typeof AuthenticatedPersonalCenterIndexRoute
}

const AuthenticatedPersonalCenterRouteRouteChildren: AuthenticatedPersonalCenterRouteRouteChildren =
  {
    AuthenticatedPersonalCenterIndexRoute:
      AuthenticatedPersonalCenterIndexRoute,
  }

const AuthenticatedPersonalCenterRouteRouteWithChildren =
  AuthenticatedPersonalCenterRouteRoute._addFileChildren(
    AuthenticatedPersonalCenterRouteRouteChildren,
  )

interface AuthenticatedContentArticleRouteRouteChildren {
  AuthenticatedContentArticleNewRoute: typeof AuthenticatedContentArticleNewRoute
  AuthenticatedContentArticleIndexRoute: typeof AuthenticatedContentArticleIndexRoute
  AuthenticatedContentArticlePostIDEditRoute: typeof AuthenticatedContentArticlePostIDEditRoute
}

const AuthenticatedContentArticleRouteRouteChildren: AuthenticatedContentArticleRouteRouteChildren =
  {
    AuthenticatedContentArticleNewRoute: AuthenticatedContentArticleNewRoute,
    AuthenticatedContentArticleIndexRoute:
      AuthenticatedContentArticleIndexRoute,
    AuthenticatedContentArticlePostIDEditRoute:
      AuthenticatedContentArticlePostIDEditRoute,
  }

const AuthenticatedContentArticleRouteRouteWithChildren =
  AuthenticatedContentArticleRouteRoute._addFileChildren(
    AuthenticatedContentArticleRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPersonalCenterRouteRoute: typeof AuthenticatedPersonalCenterRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedContentArticleRouteRoute: typeof AuthenticatedContentArticleRouteRouteWithChildren
  AuthenticatedBusinessProjectRoute: typeof AuthenticatedBusinessProjectRoute
  AuthenticatedBusinessUserRoute: typeof AuthenticatedBusinessUserRoute
  AuthenticatedContentCategoryRoute: typeof AuthenticatedContentCategoryRoute
  AuthenticatedContentColumnRoute: typeof AuthenticatedContentColumnRoute
  AuthenticatedContentConfigRoute: typeof AuthenticatedContentConfigRoute
  AuthenticatedContentResourceRoute: typeof AuthenticatedContentResourceRoute
  AuthenticatedContentTagRoute: typeof AuthenticatedContentTagRoute
  AuthenticatedOperationCommentRoute: typeof AuthenticatedOperationCommentRoute
  AuthenticatedOperationPointRoute: typeof AuthenticatedOperationPointRoute
  AuthenticatedPromotionAdvertisingRoute: typeof AuthenticatedPromotionAdvertisingRoute
  AuthenticatedPromotionSceneRoute: typeof AuthenticatedPromotionSceneRoute
  AuthenticatedSystemAdminRoute: typeof AuthenticatedSystemAdminRoute
  AuthenticatedSystemApiRoute: typeof AuthenticatedSystemApiRoute
  AuthenticatedSystemConfigRoute: typeof AuthenticatedSystemConfigRoute
  AuthenticatedSystemMenuRoute: typeof AuthenticatedSystemMenuRoute
  AuthenticatedSystemOperationLogRoute: typeof AuthenticatedSystemOperationLogRoute
  AuthenticatedSystemRoleRoute: typeof AuthenticatedSystemRoleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPersonalCenterRouteRoute:
    AuthenticatedPersonalCenterRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedContentArticleRouteRoute:
    AuthenticatedContentArticleRouteRouteWithChildren,
  AuthenticatedBusinessProjectRoute: AuthenticatedBusinessProjectRoute,
  AuthenticatedBusinessUserRoute: AuthenticatedBusinessUserRoute,
  AuthenticatedContentCategoryRoute: AuthenticatedContentCategoryRoute,
  AuthenticatedContentColumnRoute: AuthenticatedContentColumnRoute,
  AuthenticatedContentConfigRoute: AuthenticatedContentConfigRoute,
  AuthenticatedContentResourceRoute: AuthenticatedContentResourceRoute,
  AuthenticatedContentTagRoute: AuthenticatedContentTagRoute,
  AuthenticatedOperationCommentRoute: AuthenticatedOperationCommentRoute,
  AuthenticatedOperationPointRoute: AuthenticatedOperationPointRoute,
  AuthenticatedPromotionAdvertisingRoute:
    AuthenticatedPromotionAdvertisingRoute,
  AuthenticatedPromotionSceneRoute: AuthenticatedPromotionSceneRoute,
  AuthenticatedSystemAdminRoute: AuthenticatedSystemAdminRoute,
  AuthenticatedSystemApiRoute: AuthenticatedSystemApiRoute,
  AuthenticatedSystemConfigRoute: AuthenticatedSystemConfigRoute,
  AuthenticatedSystemMenuRoute: AuthenticatedSystemMenuRoute,
  AuthenticatedSystemOperationLogRoute: AuthenticatedSystemOperationLogRoute,
  AuthenticatedSystemRoleRoute: AuthenticatedSystemRoleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
